# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 863c9cba5ebfda5e6f76528c35c6d303341908bfaf5bcaab3982c2761d10fe578dd9d1b0c40262799e7e06150241c624a3e09d69d2a2daf1f321bea147c0a53e

test:
  secret_key_base: 175e845f7e07ccfb375737264f1b540cf8aca5ef59dd752de00327ce130ee41d59d1e252181c4e606514f846d718d2a22a33339bde54f4fd78692c964a002365

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
